config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :articles do
    get 'search/:tag', to: 'articles#search', as: 'search', on: :collection
  end

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :pdf_file

  def tag_text=(val)
    val = val
      .split(",")
      .map { |tag| tag.strip }
      .select { |tag| not tag.empty? }
      .map { |tag| "#{tag}," }
      .join
    super(val.to_s.strip)
  end

  def tag_list
    if tag_text
      tag_text.split(",")
    else
      []
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :load_manifest!

  private

  def load_manifest!
    # https://github.com/ztoben/assets-webpack-plugin#using-this-with-rails
    path = Rails.root.join('public', 'assets', 'manifest.json')
    file = File.read(path)
    json = JSON.parse(file)

    @scripts = []
    @styles = []

    name = controller_name && json[controller_name] ? controller_name : 'default'
    @scripts << json[name]['js']
    @styles << json[name]['css']
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
    @article.user_id = current_user.id
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /articles/search/tag
  def search
    query = ActiveRecord::Base.sanitize_sql_like params[:tag]
    @articles = Article.where "tag_text LIKE ?", "%#{query},%"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :pdf_file, :tag_text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
require 'uri'

module ArticlesHelper
  def iframe_url_for(url)
    URI.join(request.url, url)
  end
end

app/views/articles/_form.html.slim
= form_with(model: article, local: true) do |form|
  - if article.errors.any?
    #error_explanation
      h2
        = pluralize(article.errors.count, "error")
        | prohibited this article from being saved:
      ul
        - article.errors.full_messages.each do |message|
          li = message
  .field.is-horizontal
    .field-label.is-normal
      = form.label :name, class: "label"
    .field-body
      .field
        .control
          = form.text_field :name, class: "input"

  .field.is-horizontal
    .field-label.is-normal
      = form.label :pdf_file, class: "label"
    .field-body
      .field
        .file.has-name
          label.file-label
            = form.file_field :pdf_file, class: "file-input", accept: 'application/pdf'
            span.file-cta
              span.file-label
                | Choose a file…
            span.file-name
              - if article.pdf_file.attached?
                = article.pdf_file.filename
              - else
                | No file attached


  .field.is-horizontal
    .field-label.is-normal
      = form.label :tag_text, class: "label"
    .field-body
      .field
        .control
          = form.text_field :tag_text, class: "input"

  hr

  .field.is-horizontal
    .field-label
    .field-body
      .actions
        = form.submit class: "button is-success"

app/views/articles/_list.html.slim
.columns.is-multiline
  - if notice
    .column.is-full
      article.message.is-success: .message-body = notice

  - articles.each do |article|
    .column.is-half
      .card
        .card-content: article.media: .media-content
          .content
            a href="#{article_path(article)}"
              h1 = article.name

            p.buttons
              - for tag in article.tag_list do
                a.button.is-text href=search_articles_path(tag) = tag

        - if article.user_id == current_user.id
          footer.card-footer
            = link_to 'Edit', edit_article_path(article), class: 'card-footer-item has-text-success has-text-weight-semibold'
            = link_to 'Destroy', article, class: 'card-footer-item has-text-success has-text-weight-semibold', method: :delete, data: { confirm: 'Are you sure?' }

app/views/articles/edit.html.slim
== render 'shared/navbar'

.container
  .section

    .columns.is-multiline
      .column.is-full
        = render 'shared/buttons/back', href: articles_path

      .column.is-full
        .card: .card-content: article.media: .media-content: .content
          h1.title Edit Article
          hr
          = render 'form', article: @article

app/views/articles/index.html.slim
== render 'shared/navbar'

.container
  .section
    h1.title Articles
    = render 'list', articles: @articles

app/views/articles/new.html.slim
== render 'shared/navbar'

.container
  .section
    .columns.is-multiline
      .column.is-full
        = render 'shared/buttons/back', href: articles_path

      .column.is-full
        .card: .card-content: article.media: .media-content: .content
          h1.title Add New Article
          hr
          = render 'form', article: @article

app/views/articles/search.html.slim
== render 'shared/navbar'

.container
  .section
    h1.title Articles for "#{params[:tag]}"
    = render 'list', articles: @articles

app/views/articles/show.html.slim
== render 'shared/navbar'

.container
  .columns.is-gapless
    .column.is-one-third
      .section
        - if notice
          article.message.is-success: .message-body = notice

        h1.title = @article.name

        p.buttons
          - for tag in @article.tag_list do
            a.button.is-text href=search_articles_path(tag) = tag

        p.buttons
          = render 'shared/buttons/back', href: articles_path
          = render 'shared/buttons/edit', href: edit_article_path(@article)

    .column
      iframe#pdf-view src=(iframe_url_for url_for @article.pdf_file)

app/views/layouts/application.html.slim
doctype html
html
  head
    title Muse
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag *@styles
    link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP" rel="stylesheet"
  body
    == yield
  = javascript_include_tag *@scripts

app/views/shared/_icon.slim
/ name: string
/ eg. 'fa-plus' 'fa-arrow-left'
span.icon: i class="fas #{name}"

app/views/shared/_navbar.slim
nav.navbar.is-success role="navigation" aria-label="main navigation"
  .container
    .navbar-brand
      a.navbar-item.is-size-5.has-text-weight-bold href="#{root_url}"
        img src="#{root_url}/muse.svg"
      a.navbar-burger role="button" data-target="navMenu" aria-label="menu" aria-expanded="false"
        - 3.times do
          span aria-hidden="true"
    #navMenu.navbar-menu
      .navbar-end
        - if user_signed_in?
          a.navbar-item href="#{new_article_path}"
            = render 'shared/icon', name: "fa-plus"
            span.has-text-weight-semibold Add New Article
        - if user_signed_in?
          a.navbar-item href="#{destroy_user_session_path}" data-method="delete"
            = render 'shared/icon', name: "fa-sign-out-alt fa-flip-horizontal"
            span.has-text-weight-semibold Sign out

app/views/shared/buttons/_back.slim
a.button href=href
  = render 'shared/icon', name: "fa-arrow-left"
  span Back

app/views/shared/buttons/_edit.slim
a.button href=href
  = render 'shared/icon', name: "fa-edit"
  span Edit